### ISSUE TITLE
How to livestream videos rather than record?

### ISSUE THREAD

**Issue by DepinYang** [ricohapi/libuvc-theta-sample#1]
Hi, I have just bought a THETA V today, and want to bring it up on Ubuntu 16.04.

Here are my steps tried so far:
1. Clone and Compile the libuvc-theta repository. https://github.com/ricohapi/libuvc-theta/commit/05e7ba682d5761b05a9b212ef84775068fbc94e3.

2. Clone and Compile this repository. https://github.com/ricohapi/libuvc-theta-sample/commit/35efbfcec252191d13f86a40bb61a65dabde5152.

3. Link THETA V to my PC through USB.
4. Turn on and switch to the live streaming mode.
5. List devices as:

```c++
$ ./thetauvc -l
No : Product            : Serial    
 0 : RICOH THETA V      : 01105510
```

6. Run as:
```c++
$ ./thetauvc -l
start thread
start, hit any key to stop
```

But then I only see rows of numbers? How to visualize the video stream?

I and very happy to find this official new repository, and looking forward to your reply.

Thanks for your help!

**Comment by DepinYang** [comment]
I have watched this [review](https://github.com/libuvc/libuvc/pull/143/commits/f9eeff16bd59962dc350dff8ed21749e7209c6a6).

And made the modifications below at [gst_viewer.c:118](https://github.com/ricohapi/libuvc-theta-sample/blob/35efbfcec252191d13f86a40bb61a65dabde5152/gst/gst_viewer.c#L118):

```c++
    // fprintf(stderr, "%d\n", frame->data_bytes);
    FILE* fp = fopen(H264_FILE_NAME, "a");
    fwrite(frame->data, 1, frame->data_bytes, fp);
    fclose(fp);
```

Then I can successfully use `ffplay H264_FILE_NAME` to see the video.

Is there anyway to directly visualize the stream?

Thanks for the developers again! Enjoying.

**Comment by codetricity** [comment]
Are you having problems viewing it live on Ubuntu like this?  https://www.youtube.com/watch?v=kph6fKoFcZU

There is a discussion at the link below.  The sample app appears to work to display live video.
https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvdia-jetson/4359/16?u=craig

**Comment by DepinYang** [comment]
Thanks again. I have successfully brought it up, on both PC and NVIDIA TX2 installed with Ubuntu 16.04, following the instructions above.

And I have also implemented a ROS driver package for personal use. 💯

**Comment by StefanFabian** [comment]
@DepinYang Hey, we are thinking about getting a Theta V for usage with ROS, do you mind answering a few questions?

1. Do you need to manually turn it on and in to livestream mode as was necessary with the Theta S?
  We'd prefer not having to interact with the camera once its attached to the robot.
2. Can you get the raw camera images, i.e., the non-stitched images?
3. What's the maximum resolution the video feed can be streamed at?

We're also interested in the experience you had using the camera with ROS if there's anything noteworthy.
Sorry for bringing this up in a somewhat unrelated github issue but unfortunately github has no private messaging system.

**Comment by DepinYang** [comment]
@StefanFabian Hi.

1. Yes, you need to turn on and switch to the livestream mode.
2. Not directly but might-be possible. ROS wrapper based on this driver only supports stitched images. You can directly record non-stitched images on the Theta V as .MP4 videos, by pressing its button twice under the video (not livestream) mode.
3. 30Hz, 3840*1920 or 1920*960.

BTW, hardware synchronization is also an import issue. I tried temporal calibration by Kalibr successfully, but the time offset between this and other sensors are randomly distributed. Hence, I need to calibrate them each time after launch :( .

**Comment by codetricity** [comment]
You can use the USB API to switch the camera into live streaming mode with the USB cable. 

![usb_api_3](https://user-images.githubusercontent.com/5799860/93490814-cd97b380-f8bd-11ea-8b21-a28d5420ffe3.gif)

The THETA V cannot live stream dual-fisheye  However, as @DepinYang  pointed out, you can save the dual-fisheye video to file for later analysis.  

Thanks for the tip about [kalibr](https://github.com/ethz-asl/kalibr).  Does this help with calibrating two cameras for depth measurment?

**Comment by StefanFabian** [comment]
@DepinYang Thank you for your fast and thorough answer!
@codetricity But you still have to turn it on manually, right? You can't just power on the connected computer and have it turn on automatically, can you?

Considering @DepinYang's input, we will stay with insta360 airs which are unfortunately no longer produced but still in stock.
Hopefully, there'll be another plug-and-play 360 camera with higher resolution and better form-factor (a ball is quite hard to integrate in a way that it won't move after calibration) in the future.

**Comment by codetricity** [comment]
@StefanFabian , you can power it on from a Nano.

https://theta360.guide/special/linuxstreaming/

Drop in any email at the site above, go to camera.

![image](https://user-images.githubusercontent.com/5799860/93492821-1a7c8980-f8c0-11ea-83bc-3ad31a9ec8d2.png)

**Comment by idnsunset** [comment]
@codetricity, dual fisheye streaming means the image is not stiched, right?

**Comment by codetricity** [comment]
@idnsunset yes, the THETA V and Z1 cannot stream an unstitched video.  Only the THETA S can stream it unstitched.  You will need to unstitch the stream if you need it for calculations.
