### ISSUE TITLE
Is this can run on ubuntu18.04?

### ISSUE THREAD

**Issue by nonlinear1** [ricohapi/libuvc-theta-sample#3]
I have successfully installed libuvc-theta from source code from the link"https://github.com/ricohapi/libuvc-theta". Then I download libuvc-theta-sample from https://github.com/ricohapi/libuvc-theta-sample. When I run gst_viewer. It give me the following errors:start, hit any key to stop
Error: Internal data stream error.
stop
![Screenshot from 2021-03-22 18-52-00](https://user-images.githubusercontent.com/19766939/111979200-bde47a80-8b3f-11eb-8fa2-b0f003ddf999.png)
Could someone know how to solve this problem? thank you very much

**Comment by codetricity** [comment]
type in an email and access this document.
https://theta360.guide/special/linuxstreaming/
It runs on Ubuntu 18.04 with no problems.
Edit the C code to specify the /dev/video* number.  For example, if you have only one USB webcam attached to your system, /dev/video0
If you are still having problems, post at this thread. 
https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359/

We will be happy to help you in the community there.

**Comment by nonlinear1** [comment]
thank you very much!

**Comment by codetricity** [comment]
No problem.  We can help you on the forum.  BTW, I just sent you an email with a guy using the THETA with OpenVSLAM, streaming to Linux with a USB cable.  Hopefully, you can get everything work.  Good luck!

**Comment by nonlinear1** [comment]
@codetricity you are a warm-hearted person , Thank you very much！ I can run the gst_viewer of libuvc-theta-sample with your help!

**Comment by codetricity** [comment]
Great news.  Can you close the issue on GitHub?
