### ISSUE TITLE
Ubuntu to livestream with the "THETA Z1 51G" 

### ISSUE THREAD

**Issue by yukki-tanaka** [ricohapi/libuvc-theta-sample#4]
Hello 

I'm now trying to get Ubuntu to livestream with the "THETA Z1 51G" 

But, both "gst / gst_viewer" and "gst / gst_loopback" become "Error: Internal data stream error."  

What causes this ERR and how can it be resolved? 

My environment is as follows. 
****************************************
$ lsmod

~~
v4l2loopback           45056  0
~~
****************************************
$ glxinfo -B
~~
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
~~
****************************************
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
****************************************
$ ls
Makefile      gst_viewer    gst_viewer.o  thetauvc.h  v4l2loopback
gst_loopback  gst_viewer.c  thetauvc.c    thetauvc.o
****************************************
$ ./gst_loopback 
start, hit any key to stop
Error: Internal data stream error.
stop
****************************************

**Comment by yukki-tanaka** [comment]
Postscript

When I set "export GST_DEBUG =" *: 2 "and executed it, there was no" h264parse ", so I installed it and executed it again, the following ERR appeared. 

******************************************************************************************
start, hit any key to stop
0:00:01.151480951  3106 0x55a5c317ce40 WARN               decodebin gstdecodebin2.c:4678:gst_decode_bin_expose:<decodebin0> error: no suitable plugins found:
Missing decoder: H.264 (Constrained Baseline Profile) (video/x-h264, framerate=(fraction)30000/1001, stream-format=(string)avc, profile=(string)constrained-baseline, width=(int)3840, height=(int)1920, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, alignment=(string)au, level=(string)5.1, codec_data=(buffer)0142c033ffe100126742c033da00f003c6958303030368509a8001000468ce06e2)

Error: Your GStreamer installation is missing a plug-in.
stop
**********************************************************************************************************************************:
how can it be resolved?

**Comment by codetricity** [comment]
I recently recorded the process of downloading and compiling On Ubuntu 21.04 x86.

https://youtu.be/ODdIpWbsy8I

This is in addition to the previous video walkthrough with 20.04  (slightly older repo)

https://youtu.be/Ji4WDvPHzQk

This is the build on Jetson Nano

https://youtu.be/GoYi1tSIV80

There is a forum here:
https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig

This will install all gstreamer plug-ins on 20.04

$ sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio libgstreamer-plugins-base1.0-dev

I am using firmware 1.80.1 on Z1.

**Comment by yukki-tanaka** [comment]
Thank you for your answer. 

When I installed the plugin, it worked fine. 

I will close it. 

Thank you very much.
