### ISSUE TITLE
Error with gst_loopback

### ISSUE THREAD

**Issue by Yelloooowww** [ricohapi/libuvc-theta-sample#7]
Hi, I use a RICOH THRTA Z1 51G on ubuntu20.04 (x86)

gst_viewer is OK,
But I got an error when using gst_loopback
```
yellow@yellow-Acer:~/libuvc-theta-sample/gst$ ./gst_loopback 
start, hit any key to stop
Error: Device '/dev/video1' is not a output device.
stop
```

I am sure that it's vedio1.
And I have done ```sudo modprobe v4l2loopback``` without any error .

Thanks!!!

**Comment by codetricity** [comment]
if you do `lsmod |grep v4l2`, does it show the v4l2loopback module?

**Comment by Yelloooowww** [comment]
Thanks for your response, this issue has been solved. (I found that it is on /dev/video2)

In addition, I found a little bit of stream latency on both `gst_loopback` and `gst_viewer`. I think it was caused by the gstreamer pipeline set.
Could you give me some suggestions about how to modify the code on `gst_viewer.c` line 187~190 to reduce latency.
My purpose is to get the real-time image with ROS. It works well with this package (http://wiki.ros.org/video_stream_opencv) but with some latency. 

Finally, is it possible to get the live audio from theta Z1 on `/dev/video`?


Thank you very much.

**Comment by codetricity** [comment]
In case you haven't seen it, there is extensive discussion below.
https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig

The lowest latency achievable is around 250ms, possibly a bit closer to 200ms.  The camera needs to stitch the two lenses internally and thus there is a delay.  There is no way to stream unstitched dual-fisheye with the Z1/V using the USB cable.

If you are getting over 220ms latency, this guide below may help.

https://codetricity.github.io/theta-linux/optimization/

If you need 50ms latency, it is likely that you will need to use another camera (not a THETA) for robot interaction and then use the THETA as a secondary camera to capture the scene, potentially for analysis after the robot expedition. 

Audio works.  I am using it with OBS on Ubuntu now and it works. 

![image](https://user-images.githubusercontent.com/5799860/148695854-0912857d-b2f9-43b1-9338-9a33ad8dc3b3.png)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

![image](https://user-images.githubusercontent.com/5799860/148695972-a3d6cec9-498d-4ec9-a202-1cc0f7ae2288.png)
