### ISSUE TITLE
gst_viewer is opening in BLOCKING MODE

### ISSUE THREAD

**Issue by jamal-zaghmout** [ricohapi/libuvc-theta-sample#9]
Hello.
I'm having issues running the sample. I followed the READMEs on building libuvc-theta from source and building this repo but it isn't working for me.
When I run `./gst_viewer` in the `libuvc-theta-sample/gst/` directory, I get the following output:

> ```
> start, hit any key to stop
> Opening in BLOCKING MODE 
> NvMMLiteOpen : Block : BlockType = 261 
> NVMEDIA: Reading vendor.tegra.display-size : status: 6 
> NvMMLiteBlockCreate : Block : BlockType = 261 
> 
> stop
> ```

So for some reason, it is opening in blocking mode and I couldn't find the cause of the issue wherever I looked.

**Comment by codetricity** [comment]
Did you also install this:
https://github.com/ricohapi/libuvc-theta


Have you seen this thread?

https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig

advise if you're using Jetson Nano, Xavier or NX.

Try replace the decoder and sink with this:

```
“nvv4l2decoder ! nv3dsink sync=false”
```

https://github.com/ricohapi/libuvc-theta-sample/blob/f8c3caa32bf996b29c741827bd552be605e3e2e2/gst/gst_viewer.c#L192

**Comment by jamal-zaghmout** [comment]
> Did you also install this: https://github.com/ricohapi/libuvc-theta
> 
> Have you seen this thread?
> 
> https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig
> 
> advise if you're using Jetson Nano, Xavier or NX.
> 
> Try replace the decoder and sink with this:
> 
> ```
> “nvv4l2decoder ! nv3dsink sync=false”
> ```
> 
> https://github.com/ricohapi/libuvc-theta-sample/blob/f8c3caa32bf996b29c741827bd552be605e3e2e2/gst/gst_viewer.c#L192

I changed the decoder and sink and it worked! Thank you so much!

I'm also having issues with ptpcam, are you knowledgeable of ptpcam's issues on a Jetson Nano?
I tried many ptpcam commands in my terminal, and all of them give me the same error:

> could not find any device matching given bus/dev numbers

I cannot find a solution to this anywhere. Your help would be greatly appreciated.

**Comment by codetricity** [comment]
I can help with  with ptpcam too, but can you post the question on the community.theta360.guide forum and mark this issue for libuvc-theta-sample as closed?

**Comment by jamal-zaghmout** [comment]
Definitely! I'll post it right now. Thanks for your help with the initial issue.
